package com.etask.saga.orderservice.model;

public enum SourceEnum {
    ORDER_SERVICE,
    PAYMENT_SERVICE,
    SHIPPING_SERVICE,
    INVENTORY_SERVICE,
    CUSTOMER_SERVICE,
    NOTIFICATION_SERVICE,
    ACCOUNTING_SERVICE,
    PRODUCT_SERVICE,
    CART_SERVICE,
    REVIEW_SERVICE,
    WISHLIST_SERVICE,
    COUPON_SERVICE,
    PROMOTION_SERVICE,
    ANALYTICS_SERVICE,
    DELIVERY_SERVICE
}
