package com.koder.course.productreactive.mapping;

import com.koder.course.productreactive.dto.ProductCommand;
import com.koder.course.productreactive.dto.ProductResponse;
import com.koder.course.productreactive.entity.ProductEntity;
import org.springframework.stereotype.Service;

@Service
public class ProductMapper {

    public ProductEntity toEntity(ProductCommand command) {
        if (command == null) {
            return null;
        }

        return new ProductEntity(
                null, // id will be generated by the database
                command.uuid(),
                command.name(),
                command.description(),
                command.price(),
                command.stockQuantity(),
                null, // createdAt will be set to current time in the entity constructor
                null  // updatedAt will be set to current time in the entity constructor
        );
    }

    public ProductResponse toResponse(ProductEntity entity) {
        if (entity == null) {
            return null;
        }

        return new ProductResponse(
                entity.uuid(),
                entity.name(),
                entity.description(),
                entity.price(),
                entity.stockQuantity(),
                entity.createdAt(),
                entity.updatedAt()
        );
    }
}
